package ansible

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/dipeshbabu/bareplane/internal/config"
	"github.com/dipeshbabu/bareplane/internal/project"
	"gopkg.in/yaml.v3"
)

func bundleConfig() config.Config {
	cfg := inventoryConfig()
	cfg.Spec.Kubernetes = &config.KubernetesConfig{Version: "1.36.4", APIVIP: "192.168.1.100", PodCIDR: "10.244.0.0/16", ServiceCIDR: "10.96.0.0/12", KubeVIPVersion: "1.2.3", CiliumVersion: "1.20.1", KubeProxyReplacement: true}
	return cfg
}

func TestBundleDeterministicAndExcludesSecrets(t *testing.T) {
	cfg := bundleConfig()
	first, err := RenderBundle(cfg)
	if err != nil {
		t.Fatal(err)
	}
	// Changes outside the bootstrap allowlist must not affect generated bytes.
	cfg.Spec.Bootstrap.SSH.PrivateKeyFile = "/private/DO-NOT-OPEN"
	cfg.Spec.Provider.Endpoint = "https://secret-token.example.com"
	cfg.Spec.Nodes[0], cfg.Spec.Nodes[1] = cfg.Spec.Nodes[1], cfg.Spec.Nodes[0]
	second, err := RenderBundle(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatal("bundle depends on ordering or private/provider inputs")
	}
	for name, data := range first {
		if bytes.Contains(data, []byte("DO-NOT-OPEN")) || bytes.Contains(data, []byte("secret-token")) || bytes.Contains(data, []byte("privateKeyFile")) {
			t.Fatalf("secret leaked to %s", name)
		}
		if bytes.ContainsRune(data, '\r') {
			t.Fatalf("non-canonical line endings: %s", name)
		}
		if strings.HasSuffix(name, ".yaml") {
			var decoded any
			if err := yaml.Unmarshal(data, &decoded); err != nil {
				t.Fatalf("%s: %v", name, err)
			}
		}
	}
	for _, name := range []string{"inventory.yaml", "ansible.cfg", "site.yaml", "validate.yaml", "group_vars/all/cluster.yaml", "group_vars/all/connection.yaml", "roles/contract/tasks/main.yaml", "roles/contract/templates/summary.j2"} {
		if len(first[name]) == 0 {
			t.Fatalf("missing asset %s", name)
		}
	}
	first["ansible.cfg"][0] = '!'
	third, err := RenderBundle(cfg)
	if err != nil || !reflect.DeepEqual(second, third) {
		t.Fatalf("caller mutated embedded assets: %v", err)
	}
}

func TestBundleVariableValuesAndSingleControlPlane(t *testing.T) {
	cfg := bundleConfig()
	cfg.Spec.Nodes = cfg.Spec.Nodes[:1]
	delete(cfg.Spec.Bootstrap.SSH.Hosts, "lab-worker-1")
	cfg.Spec.Bootstrap.SSH.Port = 2222
	cfg.Spec.Bootstrap.SSH.Hosts["lab-control-1"] = "2001:db8::10"
	files, err := RenderBundle(cfg)
	if err != nil {
		t.Fatal(err)
	}
	var vars map[string]any
	if err := yaml.Unmarshal(files["group_vars/all/cluster.yaml"], &vars); err != nil {
		t.Fatal(err)
	}
	for key, want := range map[string]any{
		"bareplane_kubernetes_version": "1.36.4", "bareplane_cilium_version": "1.20.1", "bareplane_kube_vip_version": "1.2.3",
		"bareplane_api_vip": "192.168.1.100", "bareplane_api_port": 6443, "bareplane_pod_cidr": "10.244.0.0/16", "bareplane_service_cidr": "10.96.0.0/12",
		"bareplane_primary_control_plane": "lab-control-1", "bareplane_kube_proxy_replacement": true,
	} {
		if vars[key] != want {
			t.Fatalf("%s = %#v, want %#v", key, vars[key], want)
		}
	}
	if len(vars["bareplane_workers"].([]any)) != 0 {
		t.Fatal("workers must be an empty sequence")
	}
	if !bytes.Contains(files[InventoryFilename], []byte("2001:db8::10")) || !bytes.Contains(files[InventoryFilename], []byte("2222")) {
		t.Fatal("SSH endpoint lost")
	}
	cfg.Spec.Kubernetes = nil
	if _, err := RenderBundle(cfg); err == nil {
		t.Fatal("bundle accepted incomplete Kubernetes contract")
	}
}

// CI requires Ansible explicitly. Ordinary Go tests stay offline with no tool prerequisite.
func TestBundleAnsibleIntegration(t *testing.T) {
	ansible, err := exec.LookPath("ansible-playbook")
	if err != nil {
		if os.Getenv("BAREPLANE_TEST_ANSIBLE") == "1" {
			t.Fatal(err)
		}
		t.Skip("ansible-playbook is not installed")
	}
	for _, single := range []bool{false, true} {
		cfg := bundleConfig()
		if !single {
			// A group prefix sorts differently from its generated machine name.
			cfg.Spec.Nodes = append(cfg.Spec.Nodes, config.NodeGroup{Name: "control-0", Role: "control-plane", Count: 1, CPU: 4, MemoryGB: 8, DiskGB: 64})
			cfg.Spec.Bootstrap.SSH.Hosts["lab-control-0-1"] = "2001:db8::1"
		}
		if single {
			cfg.Spec.Nodes = cfg.Spec.Nodes[:1]
			delete(cfg.Spec.Bootstrap.SSH.Hosts, "lab-worker-1")
		}
		files, err := RenderBundle(cfg)
		if err != nil {
			t.Fatal(err)
		}
		// Exercise spaces, quotes, percent tokens, and relocation in the controller path.
		dir := filepath.Join(t.TempDir(), "project 'quoted' %h", ".bareplane", "bootstrap")
		if err := project.ReplaceGeneratedTree(dir, "bootstrap", files); err != nil {
			t.Fatal(err)
		}
		run := func(wantFailure bool, args ...string) string {
			t.Helper()
			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			cmd := exec.CommandContext(ctx, ansible, args...)
			cmd.Dir = dir
			cmd.Env = append(os.Environ(), "ANSIBLE_CONFIG="+filepath.Join(dir, "ansible.cfg"), "ANSIBLE_NOCOLOR=1")
			output, err := cmd.CombinedOutput()
			if ctx.Err() != nil || (err != nil) != wantFailure {
				t.Fatalf("%v: %v\n%s", args, err, output)
			}
			return string(output)
		}
		run(false, "--syntax-check", "site.yaml")
		out := run(false, "validate.yaml")
		if !strings.Contains(out, "1.36.4") || !strings.Contains(out, "Cilium 1.20.1") {
			t.Fatalf("template preview missing vars: %s", out)
		}
		// Evaluate the actual Ansible template, then parse it as the SSH plugin
		// does. No connection is needed to prove path quoting and token escaping.
		probe := "- hosts: all\n  gather_facts: false\n  tasks:\n    - ansible.builtin.debug:\n        msg: '{{ ansible_ssh_common_args }}'\n      run_once: true\n"
		if err := os.WriteFile(filepath.Join(dir, "probe.yaml"), []byte(probe), 0o600); err != nil {
			t.Fatal(err)
		}
		out = run(false, "probe.yaml")
		start, end := strings.Index(out, "{\n"), strings.LastIndex(out, "\n}")
		if start < 0 || end <= start {
			t.Fatalf("missing debug result: %s", out)
		}
		var result struct {
			Msg string `json:"msg"`
		}
		if err := json.Unmarshal([]byte(out[start:end+2]), &result); err != nil {
			t.Fatalf("debug JSON: %v\n%s", err, out)
		}
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		cmd := exec.CommandContext(ctx, "python3", "-c", "import json,shlex,sys; print(json.dumps(shlex.split(sys.stdin.read())))")
		cmd.Stdin = strings.NewReader(result.Msg)
		parsed, err := cmd.Output()
		cancel()
		if err != nil {
			t.Fatal(err)
		}
		var args []string
		if err := json.Unmarshal(parsed, &args); err != nil {
			t.Fatal(err)
		}
		wantPath := "UserKnownHostsFile=\"" + strings.ReplaceAll(dir+"/../state/bootstrap/known_hosts", "%", "%%") + "\""
		wantArgs := []string{"-o", "StrictHostKeyChecking=yes", "-o", "GlobalKnownHostsFile=/dev/null", "-o", wantPath}
		if !reflect.DeepEqual(args, wantArgs) {
			t.Fatalf("SSH arguments escaped incorrectly: %#v, want %#v", args, wantArgs)
		}
		for _, check := range []bool{false, true} {
			args := []string{"site.yaml"}
			if check {
				args = append(args, "--check")
			}
			out := run(true, args...)
			if !strings.Contains(out, "issue #58") || strings.Contains(out, "UNREACHABLE") {
				t.Fatalf("unavailable phase failed incorrectly: %s", out)
			}
		}
	}
}
