apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-20"
        bareplane.io/cluster: lab
        bareplane.io/component: vault
    name: lab-vault
    namespace: argocd
spec:
    destination:
        namespace: vault-secrets
        server: https://kubernetes.default.svc
    project: default
    source:
        path: components/vault
        repoURL: https://github.com/dipeshbabu/bareplane.git
        targetRevision: main
    syncPolicy:
        automated:
            allowEmpty: false
            prune: false
            selfHeal: false
        retry:
            backoff:
                duration: 5s
                maxDuration: 1m
            limit: 5
        syncOptions:
            - ServerSideApply=true
            - FailOnSharedResource=true
            - DisableClientSideApplyMigration=true
