---
- name: Inspect primary identity and initialization state
  ansible.builtin.import_tasks: inspect.yaml

- name: Initialize the primary control plane
  ansible.builtin.import_tasks: initialize.yaml
