package terraform

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/dipeshbabu/bareplane/internal/config"
	"github.com/dipeshbabu/bareplane/internal/ownership"
	"github.com/dipeshbabu/bareplane/internal/topology"
)

const (
	ProxmoxProviderSource  = "bpg/proxmox"
	ProxmoxProviderVersion = "~> 0.111.1"
	VMResourceType         = "proxmox_virtual_environment_vm"
	MainFilename           = "main.tf.json"
)

func RenderProxmox(cfg config.Config, desired topology.Topology, publicKey string) ([]byte, error) {
	if err := cfg.ValidateProvisioning(); err != nil {
		return nil, fmt.Errorf("validate provisioning configuration: %w", err)
	}
	if desired.Cluster != cfg.Metadata.Name {
		return nil, fmt.Errorf("topology cluster %q does not match configuration cluster %q", desired.Cluster, cfg.Metadata.Name)
	}

	publicKey, err := normalizePublicKey(publicKey)
	if err != nil {
		return nil, fmt.Errorf("validate SSH public key: %w", err)
	}
	settings := cfg.Spec.Provider.Proxmox
	ownershipTags, err := ownership.Tags(cfg.Metadata.Name)
	if err != nil {
		return nil, fmt.Errorf("build ownership tags: %w", err)
	}

	resources := make(map[string]any, len(desired.Machines))
	seenAddresses := make(map[string]string, len(desired.Machines))
	for _, machine := range desired.Machines {
		if machine.Target == "" {
			return nil, fmt.Errorf("machine %q has no provider target", machine.Name)
		}
		address := resourceName(machine.Name)
		if existing, exists := seenAddresses[address]; exists {
			return nil, fmt.Errorf("machines %q and %q map to the same Terraform resource name %q", existing, machine.Name, address)
		}
		seenAddresses[address] = machine.Name

		disk := map[string]any{
			"datastore_id": settings.SystemDatastore,
			"discard":      "on",
			"interface":    "scsi0",
			"iothread":     true,
			"size":         machine.DiskGB,
		}
		if strings.Contains(settings.CloudImageFileID, ":import/") {
			disk["import_from"] = tfString(settings.CloudImageFileID)
		} else {
			disk["file_id"] = tfString(settings.CloudImageFileID)
		}

		resources[address] = map[string]any{
			"agent": map[string]any{
				"enabled": false,
			},
			"cpu": map[string]any{
				"cores": machine.CPU,
			},
			"description":         tfString("Managed by Bareplane"),
			"disk":                []any{disk},
			"initialization": map[string]any{
				"datastore_id": settings.SystemDatastore,
				"ip_config": map[string]any{
					"ipv4": map[string]any{
						"address": "dhcp",
					},
				},
				"user_account": map[string]any{
					"keys":     []string{tfString(publicKey)},
					"username": tfString(settings.SSH.User),
				},
			},
			"memory": map[string]any{
				"dedicated": machine.MemoryGB * 1024,
			},
			"name":                 tfString(machine.Name),
			"network_device": []any{
				map[string]any{
					"bridge": tfString(settings.Bridge),
				},
			},
			"node_name":           tfString(machine.Target),
			"on_boot":             true,
			"operating_system": map[string]any{
				"type": "l26",
			},
			"reboot_after_update": false,
			"scsi_hardware":       "virtio-scsi-single",
			"started":             true,
			"stop_on_destroy":     true,
			"tags": []string{
				tfString(ownershipTags[0]),
				tfString(ownershipTags[1]),
			},
		}
	}

	document := map[string]any{
		"//": "Generated by Bareplane. Do not edit this file directly.",
		"provider": map[string]any{
			"proxmox": []any{
				map[string]any{
					"endpoint": tfString(cfg.Spec.Provider.Endpoint),
				},
			},
		},
		"resource": map[string]any{
			VMResourceType: resources,
		},
		"terraform": map[string]any{
			"required_providers": map[string]any{
				"proxmox": map[string]any{
					"source":  ProxmoxProviderSource,
					"version": ProxmoxProviderVersion,
				},
			},
		},
	}

	encoded, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode Terraform JSON: %w", err)
	}
	return append(encoded, '\n'), nil
}

func resourceName(machineName string) string {
	return "machine_" + strings.ReplaceAll(machineName, "-", "_")
}

func tfString(value string) string {
	value = strings.ReplaceAll(value, "${", "$${")
	return strings.ReplaceAll(value, "%{", "%%{")
}

func normalizePublicKey(value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" || strings.ContainsAny(value, "\r\n") {
		return "", fmt.Errorf("public key must be one non-empty line")
	}

	fields := strings.Fields(value)
	if len(fields) < 2 {
		return "", fmt.Errorf("public key must contain an algorithm and base64 payload")
	}
	algorithm := fields[0]
	if !strings.HasPrefix(algorithm, "ssh-") && !strings.HasPrefix(algorithm, "ecdsa-") && !strings.HasPrefix(algorithm, "sk-") {
		return "", fmt.Errorf("unsupported public key algorithm %q", algorithm)
	}
	if _, err := base64.StdEncoding.DecodeString(fields[1]); err != nil {
		return "", fmt.Errorf("public key payload is not valid base64: %w", err)
	}
	return value, nil
}
